openapi: 3.0.3
info:
  title: Property Listings API
  description: API for retrieving property listings with filtering, sorting, and pagination.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
  - url: https://property-scraper.glitch.me
    description: Production server
paths:
  /api/listings:
    get:
      summary: Get property listings
      description: Retrieve a paginated list of property listings with optional filtering and sorting.
      parameters:
        - name: minPrice
          in: query
          description: Minimum price filter
          schema:
            type: integer
        - name: maxPrice
          in: query
          description: Maximum price filter
          schema:
            type: integer
        - name: location
          in: query
          description: Location filter (case-insensitive substring match)
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination (default: 1)
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of listings per page (default: 10)
          schema:
            type: integer
            default: 10
        - name: sortField
          in: query
          description: Field to sort by (title, price, location)
          schema:
            type: string
            enum: [title, price, location]
            default: price
        - name: sortDirection
          in: query
          description: Sort direction (asc or desc)
          schema:
            type: string
            enum: [asc, desc]
            default: asc
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  listings:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        price:
                          type: number
                        location:
                          type: string
                        link:
                          type: string
                  pagination:
                    type: object
                    properties:
                      currentPage:
                        type: integer
                      totalPages:
                        type: integer
                      totalItems:
                        type: integer
                      itemsPerPage:
                        type: integer
        '404':
          description: No listings data available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string